drop table if exists products;
create table products
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    name VARCHAR(30) not null,
    weight float,

    visible boolean default true not null,
    deleted datetime,

    dto object
);

insert into PRODUCTS(name, weight) values ('1', 1.2);
insert into PRODUCTS(name) values ('2');
insert into PRODUCTS(name, visible) values ('3', false);

insert into PRODUCTS(name, deleted) values ('4', current_timestamp);
